### ISSUE TITLE
pre-trained model can't download

### ISSUE THREAD

**Issue by V1lu0** [litun5315/SS-watermark#2]
Have you saved the model? Can it be provided? thank

**Comment by l1teng** [comment]
Hi, sorry for the late reply. After inspecting the original model repo (github.com/tancik/StegaStamp), I found the authors had deleted the checkpoint urls from the README file.

https://github.com/tancik/StegaStamp/commit/c984446048b826587ca1875027b0a1dc1885fb30

This repo has been no longer maintained for a while, and we did not save the checkpoints. Sorry about that.

If the computing sources are available, maybe you can consider training your own network using the following guidance.

https://github.com/tancik/StegaStamp#detector

Or consult the authors of StegaStamp.
